/**
 * Application-wide shared constants.
 * Import from here instead of hard-coding values in components.
 */

/**
 * Manufacturer specialty categories used in the B2B directory search
 * and in the manufacturer profile keyword selection.
 */
export const MANUFACTURER_CATEGORIES: string[] = [
  'Deri',
  'Gümüş',
  'Altın',
  'Ahşap',
  'Takı',
  'Bijuteri',
  'Terzi',
  'Lazer Kesim',
];

/**
 * Türkiye'nin 81 ili (alfabetik). Üretici profili şehir seçimi ve üretici bul
 * şehir filtresi bu listeden, aramalı dropdown (CitySelect) ile seçim yapar.
 */
export const TURKISH_PROVINCES: string[] = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Aksaray',
  'Amasya',
  'Ankara',
  'Antalya',
  'Ardahan',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bartın',
  'Batman',
  'Bayburt',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Düzce',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkâri',
  'Hatay',
  'Iğdır',
  'Isparta',
  'İstanbul',
  'İzmir',
  'Kahramanmaraş',
  'Karabük',
  'Karaman',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırıkkale',
  'Kırklareli',
  'Kırşehir',
  'Kilis',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Mardin',
  'Mersin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Osmaniye',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Şanlıurfa',
  'Şırnak',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Uşak',
  'Van',
  'Yalova',
  'Yozgat',
  'Zonguldak',
];

export const ROLES = {
  SELLER: 'seller',
  MFR: 'mfr',
  ADMIN: 'admin',
} as const;

export const ORDER_STATUS = {
  AWAITING: 'awaiting',
  PRODUCTION: 'production',
  COMPLETED: 'completed',
  DELIVERED: 'delivered',
  BROKEN: 'broken',
  CORRECTED: 'corrected',
  DEFECTIVE: 'defective',
  MISSING: 'missing',
  TO_SHIP: 'to_ship',
  SHIPPED: 'shipped',
  CANCELLED: 'cancelled',
} as const;
